### ISSUE TITLE
Error when activate/deactivate alarm

### ISSUE THREAD

**Issue by teocannata** [Minims/homeassistant-addons#19]
Hi,
Since some day ago I'm getting following error whenever I try to change alarm mode:

`2023-02-22 20:35:59,639 [ERROR] [business.mqtt:197] Error when processing message: list index out of range`

I'm the only one?

Thanks!
Matteo

**Comment by teocannata** [comment]
After the third time a rebuilt the integration it restarted working well for activation. Don't know why.
The only thing is not working yet is night mode

**Comment by Minims** [comment]
What Is the issue with Night mode ?

**Comment by teocannata** [comment]
Just tried, same error in log. 

``2023-02-28 00:12:34,287 [ERROR] [business.mqtt:197] Error when processing message: list index out of range ``

I cannot activate Night mode

**Comment by Minims** [comment]
Hello, i will need a bit more log, before and after the error, and maybe in debug mode.
Are you using 0.2.9 or dev version ? 
I have update the dev version to get a more detailed log too

**Comment by teocannata** [comment]
I'm using 0.2.9 prod version, should I switch to dev repo to give you a better log?
If useful I tried same command with debug enabled:
```
[business:247] Update Casa Status
2023-03-01 21:26:21,436 [DEBUG] [mqtt:64] Message published: 280
2023-03-01 21:26:28,261 [DEBUG] [mqtt:54] Message received on somfyProtect2mqtt/MCq1SCdppBEo18C4oMfIze4onDMoQacx/command: b'ARM_HOME'
2023-03-01 21:26:28,262 [ERROR] [business.mqtt:197] Error when processing message: list index out of range
++Sent raw: b'\x89\x80=\xafV\x82'
2023-03-01 21:26:28,770 [DEBUG] [websocket:78] ++Sent raw: b'\x89\x80=\xafV\x82'
++Sent decoded: fin=1 opcode=9 data=b''
2023-03-01 21:26:28,772 [DEBUG] [websocket:78] ++Sent decoded: fin=1 opcode=9 data=b''
++Rcv raw: b'\x8a\x00'
2023-03-01 21:26:28,819 [DEBUG] [websocket:78] ++Rcv raw: b'\x8a\x00'
++Rcv decoded: fin=1 opcode=10 data=b''
2023-03-01 21:26:28,821 [DEBUG] [websocket:78] ++Rcv decoded: fin=1 opcode=10 data=b''
2023-03-01 21:26:31,446 [DEBUG] [schedule:660] Running job Job(interval=10, unit=seconds, 
```

**Comment by teocannata** [comment]
I tried switching to dev version, below the error trying to switch to Night Mode:

`[business.mqtt:177] Error when processing message: list index out of range: <paho.mqtt.client.MQTTMessage object at 0x7fbb5f99e0>`

**Comment by Minims** [comment]
I have update again dev version for log.
Can you click on REBUILD / RECONTRUIRE in the addon.
Then can you give me the new log.

**Comment by teocannata** [comment]
Great, thank you. Below new log:
```
2023-03-02 07:39:53,028 [INFO] [business:230] Update Casa Status
2023-03-02 07:40:01,568 [ERROR] [business.mqtt:177] Error when processing message: list index out of range: somfyProtect2mqtt/MCq1SCdppBEo18C4oMfIze4onDMoQacx/command =>b'ARM_HOME'
2023-03-02 07:40:03,041 [INFO] [business:226] Update Sites Status
2023-03-02 07:40:03,317 [INFO] [business:230] Update Casa Status
2023-03-02 07:40:13,330 [INFO] [business:226] Update Sites Status
2023-03-02 07:40:13,731 [INFO] [business:230] Update Casa Status
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/websocket/_app.py", line 274, in _send_ping
    self.sock.ping(self.ping_payload)
  File "/usr/lib/python3.9/site-packages/websocket/_core.py", line 338, in ping
    self.send(payload, ABNF.OPCODE_PING)
  File "/usr/lib/python3.9/site-packages/websocket/_core.py", line 283, in send
    return self.send_frame(frame)
  File "/usr/lib/python3.9/site-packages/websocket/_core.py", line 311, in send_frame
    l = self._send(data)
  File "/usr/lib/python3.9/site-packages/websocket/_core.py", line 525, in _send
    return send(self.sock, data)
  File "/usr/lib/python3.9/site-packages/websocket/_socket.py", line 170, in send
    return _send()
  File "/usr/lib/python3.9/site-packages/websocket/_socket.py", line 147, in _send
    return sock.send(data)
  File "/usr/lib/python3.9/ssl.py", line 1176, in send
    return super().send(data, flags)
OSError: [Errno 9] Bad file descriptor
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.9/site-packages/websocket/_app.py", line 276, in _send_ping
    _logging.debug("Failed to send ping: %s", ex)
TypeError: debug() takes 1 positional argument but 2 were given
2023-03-02 07:40:19,716 [ERROR] [somfy_protect.websocket:106] Error in the websocket connection: Connection to remote host was lost.
2023-03-02 07:40:19,717 [ERROR] [websocket:62] Connection to remote host was lost. - goodbye
2023-03-02 07:40:19,718 [INFO] [somfy_protect.websocket:110] Reconnecting
2023-03-02 07:40:21,975 [INFO] [websocket:74] Websocket connected
2023-03-02 07:40:21,980 [INFO] [somfy_protect.websocket:67] Websocket Connection is READY
2023-03-02 07:40:23,745 [INFO] [business:250] Update Devices Status
```

**Comment by Minims** [comment]
What did you have in the alarm card in Lovelace dashboard ?

"ARM_HOME" is not a valid status for alarm.

What is supported is "armed_night", "disarmed", and "armed_away"

```
type: alarm-panel
states:
  - arm_night
  - arm_away
entity: alarm_control_panel.maison
```

**Comment by teocannata** [comment]
I have a button-card just used to tap and get the more-info page and I usually switch inside it.
Below you can find the place where I usually switch the alarm... It's an Italian version but I hope is anyway understandable :
![Screenshot_2023-03-02-21-40-16-467-edit_io homeassistant companion android](https://user-images.githubusercontent.com/48519570/222547042-863f92e7-46c6-4f9b-8aef-e5158f889af5.jpg)


I was used to have three possible states: armed_away, armed_night and disarmed.
On those my card is just changing color of the icon.

**Comment by Minims** [comment]
Can you edit the card and select Armed_night ? 

![Capture d’écran 2023-03-02 à 21 58 50](https://user-images.githubusercontent.com/1724785/222551156-d2b0a2b0-a394-489a-bc7b-60f084fc4ff6.png)

**Comment by teocannata** [comment]
You were right, adding the dedicated card that is customizable it works!
So the problem is only mine, because I would like to keep working with more-info page that I guess is not customizable.
It was working, maybe I created an automation to automatically manage armed_night/armed_home but I don't remember.
By the way thank you for you're help! I will study a solution that fits my needs 😊

**Comment by teocannata** [comment]
Just found a solution, I'm sharing below.
I built an automation like this, with my topic:
```
alias: Alarm Night/Home
description: ""
trigger:
  - platform: mqtt
    topic: somfyProtect2mqtt/xxxxxxxxxxxxxxx/command
    payload: ARM_HOME
condition: []
action:
  - service: alarm_control_panel.alarm_arm_night
    data: {}
    target:
      entity_id: alarm_control_panel.casa
mode: single

```
